import { NextRequest, NextResponse } from 'next/server';

export async function GET(
  request: NextRequest,
  { params }: { params: { shareId: string } }
) {
  try {
    const shareId = params.shareId;
    
    // Mock share settings
    const shareSettings = {
      id: shareId,
      reportId: 'report-1',
      title: 'Q4 2024 Financial Analysis',
      description: 'Comprehensive financial analysis for Q4 2024',
      isPublic: true,
      password: null,
      expiresAt: null,
      allowDownload: true,
      allowComments: false,
      viewCount: Math.floor(Math.random() * 100),
      createdAt: new Date('2024-01-01'),
      updatedAt: new Date(),
    };

    // Check if password is required
    const password = request.headers.get('x-password');
    if (shareSettings.password && shareSettings.password !== password) {
      return NextResponse.json(
        { error: 'Password required' },
        { status: 401 }
      );
    }

    // Check if expired
    if (shareSettings.expiresAt && shareSettings.expiresAt < new Date()) {
      return NextResponse.json(
        { error: 'Share link has expired' },
        { status: 410 }
      );
    }

    // Mock report data
    const report = {
      id: shareSettings.reportId,
      title: shareSettings.title,
      description: shareSettings.description,
      sections: [
        {
          id: 'intro',
          type: 'text',
          title: 'Executive Summary',
          content: `
            <h2>Executive Summary</h2>
            <p>This is a comprehensive financial analysis report generated by AssetWorks AI. The report provides detailed insights into market trends, financial performance, and strategic recommendations.</p>
            <p>Key highlights include:</p>
            <ul>
              <li>Revenue growth of 15% year-over-year</li>
              <li>Strong performance in European markets</li>
              <li>Strategic initiatives showing positive ROI</li>
            </ul>
          `,
          aiPrompt: 'Create an executive summary for a financial report',
          editable: false,
          order: 1,
        },
        {
          id: 'analysis',
          type: 'text',
          title: 'Financial Analysis',
          content: `
            <h2>Financial Analysis</h2>
            <p>Our comprehensive analysis reveals several key trends and opportunities:</p>
            <h3>Revenue Analysis</h3>
            <p>Total revenue reached $125M in Q4 2024, representing a 15% increase compared to the previous quarter. This growth was primarily driven by:</p>
            <ul>
              <li>New product launches contributing 40% of growth</li>
              <li>Market expansion in European territories</li>
              <li>Improved customer retention rates</li>
            </ul>
            <h3>Cost Management</h3>
            <p>Operating expenses were well-controlled, with a 8% increase year-over-year, primarily due to strategic investments in technology and talent acquisition.</p>
          `,
          aiPrompt: 'Generate detailed financial analysis',
          editable: false,
          order: 2,
        },
      ],
      metadata: {
        author: 'AssetWorks AI',
        version: '1.0',
        tags: ['financial', 'analysis', 'q4-2024'],
      },
      dataSources: [],
      createdAt: new Date('2024-01-01'),
      updatedAt: new Date('2024-01-15'),
      status: 'published',
    };

    return NextResponse.json({
      success: true,
      report,
      shareSettings,
    });
  } catch (error) {
    return NextResponse.json(
      { 
        success: false,
        error: 'Failed to load shared report',
        details: error instanceof Error ? error.message : 'Unknown error'
      },
      { status: 500 }
    );
  }
}
